### PR TITLE
Circuitpython doc move

### PR DESCRIPTION
**Pull request by jepler**
This builds on #423 and also works together with https://github.com/adafruit/circuitpython/pull/5028 to complete the doc move. (If we take this PR, then #423 is moot)

However, this build will come up in red for the circuitpython builds because without https://github.com/adafruit/circuitpython/pull/5028 (which renames some use of ulab.ndarray to ulab.numpy.ndarray within our own pyi/docs) it is still not OK.

I didn't find a way for both things to work together, so the possibility I see is to (approximately in order):

- [ ] verify that https://github.com/adafruit/circuitpython/pull/5028 is green & approved
- [x] verify that this PR is green for micropython & approved
- [ ] merge this PR
- [ ] release ulab
- [ ] Update https://github.com/adafruit/circuitpython/pull/5028 with the released ulab
- [ ] merge https://github.com/adafruit/circuitpython/pull/5028

then we can all be green again.

Closes: #419

### CODE REVIEW

**Comment by v923z** [comment]
@jepler  OK, I will look at it later today. Thanks for following up on this!

**Comment by v923z** [comment]
@jepler Jeff, thanks again for taking care of this! I don't see any problems here, so we can merge the PR. (I don't know if your list is chronological, i.e., whether the approval of the first point must precede that of the second). I can prepare a release, no problem. I believe, there are two new functions/methods since the last release.

**Comment by jepler** [comment]
It's semi-chronological, so green + approved on the circuitpython PR is what I'd wait for next.

**Comment by jepler** [comment]
I think I found a way that gives forward compatibility, so if this turns out green I'll merge it.

**Comment by v923z** [comment]
> I think I found a way that gives forward compatibility, so if this turns out green I'll merge it.

Fine with me.

**Comment by jepler** [comment]
@v923z yay -- ping me when you have had time to make a release and I'll start the ball rolling in circuitpython to pull that version in. Thanks for doing the initial work on this doc stuff as well!

**Comment by v923z** [comment]
@jepler I can create a tag before 1pm, your time.

**Pull request merged**
