### PR TITLE
Remove debug output from code/usermod.cmake

### PR DESCRIPTION
**Pull request by Gadgetoid**
I'd left some very noisy warning messages in `usermod.cmake`, this patch removes them for a quieter, happier build.

### CODE REVIEW

**Comment by Gadgetoid** [comment]
Don't merge this just yet- there are likely to be a few other changes to this file to match changes I'm now making to the upstream PR and it seems sensible to add them as commits here.

**Comment by Gadgetoid** [comment]
Added some commits to bring this in line with the suggestions here - https://github.com/micropython/micropython/pull/6960

**Comment by v923z** [comment]
> Don't merge this just yet- there are likely to be a few other changes to this file to match changes I'm now making to the upstream PR and it seems sensible to add them as commits here.

@Gadgetoid Philip, just ping me, when you this the PR is complete!

**Comment by v923z** [comment]
@Gadgetoid Philip, do you think you could consolidate your build instructions into a script like this: https://github.com/v923z/micropython-ulab/tree/master/build?

**Comment by Gadgetoid** [comment]
> @Gadgetoid Philip, do you think you could consolidate your build instructions into a script like this: https://github.com/v923z/micropython-ulab/tree/master/build?

Done! Hopefully in the spirit of what you're after.

I've checked for the existence of both `micropython` and `ulab` directories in the `build` directory, but also checked for `../code` to avoid cloning `ulab` if you run the `rp2.sh` script in a local copy of the source.

**Comment by v923z** [comment]
> > @Gadgetoid Philip, do you think you could consolidate your build instructions into a script like this: https://github.com/v923z/micropython-ulab/tree/master/build?
> 
> Done! Hopefully in the spirit of what you're after.

No, it is actually better. Thanks a bunch!

**Comment by v923z** [comment]
@Gadgetoid Philip, does https://github.com/micropython/micropython/pull/6960 mean that we can now remove the reference to your fork from the build instructions/script? We should probably do that before you take the fork down :wink:

**Comment by Gadgetoid** [comment]
alakazam alakazoo something something I'm way ahead of you #356

Well I would have been if I'd raised this as a PR 5 hours ago when I actually wrote it :laughing:

Busy day!

**Pull request merged**
