### PR TITLE
fix: remove make axtls, added make submodules

### PR DESCRIPTION
**Pull request by tejalbarnwal**
There has been an update with the new build instructions for micropython as found [here](https://github.com/micropython/micropython#the-unix-version)

### CODE REVIEW

**Comment by v923z** [comment]
Thanks for the comments! I remove `axtls` from the build script. https://github.com/v923z/micropython-ulab/pull/540 passes with `micropython`. We are working on the `circuitpython` CI, but that is a different issue: https://github.com/v923z/micropython-ulab/issues/541

**Comment by v923z** [comment]
What I wanted to say is that the other PR should actually contain the fix for this.

**Comment by tejalbarnwal** [comment]
Just to confirm, I ran `build.sh` while commenting the line to run the test scripts. I am referring to the below code line
```bash
bash test-common.sh "${dims}" "micropython/ports/unix/micropython-$dims"
```
The above line interrupts the build process because `gc.py` fails the test case.
image

The `gc.py.exp` is as follows
```
988.0000000000001
array([1.0, 1.0, 1.0, ..., 1.0, 1.0, 1.0], dtype=float64)
988.0000000000001
array([1.0, 1.0, 1.0, ..., 1.0, 1.0, 1.0], dtype=float64)
```
`gc.py.out` gives the following:
```
988.0
array([1.0, 1.0, 1.0, ..., 1.0, 1.0, 1.0], dtype=float64)
988.0
array([1.0, 1.0, 1.0, ..., 1.0, 1.0, 1.0], dtype=float64)
```
Am not sure why does it fails the test

**Comment by v923z** [comment]
Again, the CI produces no errors on `micropython`: https://github.com/v923z/micropython-ulab/runs/7528073593?check_suite_focus=true

**Comment by tejalbarnwal** [comment]
Right! Thank you

**Comment by v923z** [comment]
I think this PR is no longer needed.

**Pull request closed without merging**
