### PR TITLE
Adding branch release/v1.7 to suit version 1.7.9

### PR DESCRIPTION
**Pull request by RobertoRoos**
New branch needs to be created and PR needs to be retargeted.

Example build is here: https://micropython-ulab-robert.readthedocs.io/en/1.7.9/

Relates to #443

### CODE REVIEW

**Comment by RobertoRoos** [comment]
I updated with the latest `conf.py` and now it builds. I have to admit I haven't looked at the built output in detail, I just assume the output fails or is correct.

**Comment by RobertoRoos** [comment]
Nonono, this isn't supposed to go into the `legacy` branch. All these versions should have their own branch, but I don't have the power to create branches here.

Can you force push this merge out? And then retarted this PR?

**Comment by v923z** [comment]
@RobertoRoos I think 1.7.9 is OK here, because 1.7.8 was at the end of the legacy branch. So, in that case, we can continue there in a linear fashion. 
On the other hand, 0.36, and 0.54.4 should have their own branches, which I created.

**Comment by RobertoRoos** [comment]
@v923z yeah I see now. Thanks for merging!

Yeah, I'm having my doubts about those versions now 😅
Funny thing is we now have the ticket to also update our plan version...

**Pull request merged**
