### PR TITLE
add script to test polynomial module

### PR DESCRIPTION
**Pull request by mouryarahul**
This branch contains the script to test polynomial fitting functions:

1. ulab.polyval

1. ulab.polyfit

### CODE REVIEW

**Comment by v923z** [comment]
@mouryarahul Rahul, could you, please, rename this as `poly.py`, because `polyval.py` is misleading.

**Comment by mouryarahul** [comment]
> @mouryarahul Rahul, could you, please, rename this as `poly.py`, because `polyval.py` is misleading.

@v923z in `tests\numpy` there is an existing file `poly.py` and `poly.py.exp`. So,  I will rename the `polyva.py` to `poly_extra.py`.

**Comment by v923z** [comment]
> > @mouryarahul Rahul, could you, please, rename this as `poly.py`, because `polyval.py` is misleading.
> 
> @v923z in `tests\numpy` there is an existing file `poly.py` and `poly.py.exp`. So, I will rename the `polyva.py` to `poly_extra.py`.

You should really either combine the two scripts, or get rid of the old one. It will quickly become unmanagable, if we have tests for one function in two places.

**Comment by mouryarahul** [comment]
> > > @mouryarahul Rahul, could you, please, rename this as `poly.py`, because `polyval.py` is misleading.
> > 
> > 
> > @v923z in `tests\numpy` there is an existing file `poly.py` and `poly.py.exp`. So, I will rename the `polyva.py` to `poly_extra.py`.
> 
> You should really either combine the two scripts, or get rid of the old one. It will quickly become unmanagable, if we have tests for one function in two places.

@v923z `poly_extra` includes all the tests in `poly`, so I'll delete the `poly`.

**Pull request merged**
