### PR TITLE
Lowercase MP macros

### PR DESCRIPTION
**Pull request by tannewt**
We're updating to newer MP in CircuitPython and will no longer have the upper case versions.

### CODE REVIEW

**Comment by v923z** [comment]
@tannewt Scott, this fails with an implicit declaration of the macro: https://github.com/v923z/micropython-ulab/pull/370/checks?check_run_id=2421432960

**Comment by tannewt** [comment]
This is because we haven't updated CircuitPython yet. The pending PR is: https://github.com/adafruit/circuitpython/pull/4649 Once it's merged then we can get this to pass and then update CP back to upstream.

**Comment by v923z** [comment]
> This is because we haven't updated CircuitPython yet. The pending PR is: 

Thanks! I leave this open then. I have subscribed to that thread.

**Comment by v923z** [comment]
@tannewt Thanks a lot, Scott!

**Pull request merged**
