### PR TITLE
Ardupy openmv

### PR DESCRIPTION
**Pull request by Crazyhackelkorn**
The legacy build had worked for me with ArduPy (micropython v1.11) but for compatibility with other HW which uses ulab 2.1.5. i made some changes so it works for me again.

Maybe it works for other micropython versions, too.

### CODE REVIEW

**Comment by v923z** [comment]
> The legacy build had worked for me with ArduPy (micropython v1.11) but for compatibility with other HW which uses ulab 2.1.5. i made some changes so it works for me again.

I am a bit confused: the legacy branch ends with version 1.7. Version 2.0+ has  a different syntax. Do you want to merge the changes into the master branch, or legacy?

**Comment by Crazyhackelkorn** [comment]
Sry for the confusion. it's for the master branch. I don't know if my changes make sense to merge with the master. I'm very new to Contributing to software on github. This are minimal changes which work for me. If you think this make no know Sense. Then I will use my fork with ArduPy.

I don't know if the OPENMV define is a relic of the old version or if some Micropython ports use it for ulab 2.0+.

I think that maybe my first commit with the relative paths can make sense for the master branch.

**Comment by v923z** [comment]
> 
> I don't know if the OPENMV define is a relic of the old version or if some Micropython ports use it for ulab 2.0+.

`openmv` has switched to `micropython` v.1.13 recently. In the past, they based their code on `micropython` v.1.11, and that didn't support the advanced slicing, and that is why we had to add the those functions. 

What stands in the way of upgrading `ardupy` to a newer version of `micropython`? 1.11 is rather old now...

**Comment by Crazyhackelkorn** [comment]
> What stands in the way of upgrading ardupy to a newer version of micropython? 1.11 is rather old now...

normaly I think nothing. But i have done this work for an education projekt. And it's almost finished. So I don't have time to upgrade and test it.

Sry if i had bothered you with this PR.

**Comment by v923z** [comment]
@Crazyhackelkorn Stephan, I wasn't trying to argue against the PR. I am more than happy to merge the changes, if you wish. Just re-open the PR.

**Comment by Crazyhackelkorn** [comment]
@v923z I have changed the ```#ifdef OPENMV```to ```#if MICROPY_VERSION_MAJOR == 1 && MICROPY_VERSION_MINOR == 11```

Because has you have said

> ```openmv``` has switched to ```micropython``` v.1.13 recently. In the past, they based their code on ```micropython``` v.1.11, and that didn't support the advanced slicing, and that is why we had to add the those functions.

It's a specific porblem with ```micropython``` v.1.11

**Comment by v923z** [comment]
> @v923z I have changed the `#ifdef OPENMV`to `#if MICROPY_VERSION_MAJOR == 1 && MICROPY_VERSION_MINOR == 11`

Thanks! I forgot to spell it out yesterday that this is probably a better solution.

**Pull request merged**
